" VIMRC

" maintainer: Tommy Chu
" github: chutommy
" email: tommychu2256@gmail.com

" syntax
syntax on
filetype plugin indent on

" chars
set encoding=utf-8

" system menu
set wildmenu

" disable mouse
set mouse-=a

" share system clipboard
set clipboard=unnamedplus

" error bell
set noerrorbells

" autocheck
set autowrite
"set autoread
"set lazyredraw

" history
set history=1000
"set formatoptions+=j

" backspace behavior
set backspace=indent,eol,start

" split
set splitright
set splitbelow

" white symbols
set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set smartindent
set expandtab

" invisible chars
set list
set listchars=tab:··>,trail:·,nbsp:_

" movement
set virtualedit=block
"set wrap
set scrolloff=4
set sidescrolloff=4

" search
"set ignorecase
set smartcase
set incsearch
set hlsearch

" numbers
set number
set relativenumber

" cursor
set cursorline
set cursorlineopt=line
set cursorcolumn

" meta data
set ruler
set showcmd
set showmode

" brackets
set showmatch
set matchtime=2

" colors
"colorscheme morning
colorscheme evening
"colorscheme desert
set t_Co=256
set termguicolors
set background=dark

" statusline
set laststatus=2
set statusline=
set statusline+=\ %F\ %M\ %Y\ %R\ %W
set statusline+=%=
set statusline+=\ ascii:\ %b\ hex:\ 0x%B\ row:\ %l\ col:\ %c\ percent:\ %p%%
