" VIMRC

" maintainer: Tommy Chu
" github: chutommy
" email: tommychu2256@gmail.com

" syntax
syntax on
filetype plugin indent on

" error bell
set noerrorbells

" chars
set encoding=utf-8
set autowrite
set autoread

" backspace behavior
set backspace=indent,eol,start
set clipboard=unnamed

" split
set splitright
set splitbelow

" white symbols
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent
set smartindent
set mouse-=a
set virtualedit=block

" search
set ignorecase
set smartcase

" menu
set wildmenu
set lazyredraw

" history
set history=666
set formatoptions+=j

" invisible chars
set listchars=tab:\.\ ,trail:·,eol:¬,nbsp:_

" popup menu
set pumblend=25

" snumbers
set list
set number
set relativenumber

" cursor
set cursorline
set cursorcolumn

" cmd config
set showcmd
set showmatch
set noshowmode

" search highlighting
set incsearch
set hlsearch

" movement
set wrap
set scrolloff=4
set sidescrolloff=4

" colors
set t_Co=256
set termguicolors
set background=dark

" clipboard
" copy
vnoremap  <leader>y  "+y
nnoremap  <leader>Y  "+yg_
nnoremap  <leader>y  "+y
nnoremap  <leader>yy  "+yy
" paste
nnoremap <leader>p "+p
nnoremap <leader>P "+P
vnoremap <leader>p "+p
vnoremap <leader>P "+P

" highlight
nnoremap <C-s> :call ClearSearch()<CR>:nohl<CR>
function! ClearSearch()
    let @/=""
endfunction

" shifting
nnoremap <Tab> >>_
nnoremap <S-Tab> <<_
vnoremap <Tab> >gv
vnoremap <S-Tab> <gv

" fast moving
noremap <S-l> 4l
noremap <S-h> 4h
noremap <C-j> 8j
noremap <C-k> 8k
